version: "3.9"
services:
    nginx:
        image: ghcr.io/unyacat/illuststore_nginx:latest
        ports:
            - "7776:8080" #Change to X:8080 to access on port X
        depends_on:
            - frontend

    frontend:
        image: ghcr.io/unyacat/illuststore_frontend:latest
        depends_on:
            - backend

    backend:
        image: ghcr.io/unyacat/illuststore_backend:latest
        restart: always
        environment:
            PGSTRING: postgres://postgres:example@db:5432/postgres # This string has to resolve to a Postgres database on version 11
        volumes:
            - ./media/:/code/media
        depends_on:
            - db

    deepdanbooru:
        build:
            context: ./deepdanbooru
            dockerfile: Dockerfile
        volumes:
            - ./media/:/media/
        environment:
            BASE_ADDRESS: backend:4000
            FETCH_INTERVAL: 5
        restart: always


    db:
        image: postgres:11
        restart: always
        environment:
            POSTGRES_PASSWORD: example
        volumes:
            - ./data/:/var/lib/postgresql/data