name: build_latest_push_ghcr

on:
  push:
      branches: [ main ]
  workflow_dispatch:

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: unyacat
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: frontend
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/illuststore_backend:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # build_search:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1
  #     -
  #       name: Login to GitHub Container Registry
  #       uses: docker/login-action@v1
  #       with:
  #         registry: ghcr.io
  #         username: unyacat
  #         password: ${{ secrets.CR_PAT }}

  #     - name: Build and push
  #       uses: docker/build-push-action@v2
  #       with:
  #         context: search
  #         push: true
  #         file: ./search/Dockerfile
  #         tags: |
  #           ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
  #     -
  #       name: Image digest
  #       run: echo ${{ steps.docker_build.outputs.digest }}

  build_backend:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: unyacat
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: backend
          push: true
          file: ./backend/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/illuststore_backend:latest

      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  build_nginx:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: unyacat
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: nginx
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/illuststore_nginx:latest
          file: ./nginx/Dockerfile
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # build_autoimport:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     -
  #       name: Set up QEMU
  #       uses: docker/setup-qemu-action@v1
  #     -
  #       name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v1